INHERIT: ../zh/mkdocs.yml

extra:
  analytics: 
    provider: google
    property: G-RMREXXKJEQ
    feedback:
      title: 這個頁面對你是否有幫助
      ratings:
        - icon: material/emoticon-happy-outline
          name: 這個頁面很有幫助
          data: 1
          note: >-
            感謝你的反饋!
        - icon: material/emoticon-sad-outline
          name: 此頁面有待改進
          data: 0
          note: >- 
            感謝你的反饋！使用我們的<a href="..." target="_blank" rel="noopener">反饋表</a>.帮助我们改进此页面